name: mosya
description: Mobil Syariah

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    flutter_svg: ^1.0.3
    page_transition: ^2.0.5
    cupertino_icons: ^1.0.2
    fluttertoast: ^8.0.9
    firebase_core: ^1.16.0
    google_sign_in: ^5.3.1
    shared_preferences: ^2.0.15
    dio: ^4.0.6
    http: ^0.13.4
    objectbox: ^1.6.0
    objectbox_flutter_libs: any
    encrypt: ^5.0.1
    flutter_launcher_icons: ^0.9.2
    pin_code_fields: ^7.4.0
    # for ObjectBox Sync use this dependency instead:
    # objectbox_sync_flutter_libs: any

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.0.0
    objectbox_generator: any

flutter_icons:
    android: launcher_icon
    ios: true
    image_path: assets/images/app_icon.png

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/svg/

    fonts:
        - family: OpenSans
          fonts:
              - asset: assets/fonts/opensans_light.ttf
              - asset: assets/fonts/opensans_regular.ttf
              - asset: assets/fonts/opensans_bold.ttf
                weight: 700

        - family: Roboto
          fonts:
              - asset: assets/fonts/roboto_regular.ttf
              - asset: assets/fonts/roboto_medium.ttf
              - asset: assets/fonts/roboto_bold.ttf
                weight: 700

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
